[package]
name = "special_relativity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
tobj = "4.0.0"
vecmath = "1.0.0"
rayon = "1.8"
